[".config/alacritty/themes"]
refreshPeriod = "0"
type = "git-repo"
url = "https://github.com/alacritty/alacritty-theme.git"

["./bin/rsync_tmbackup.sh"]
type = "file"
url= "https://raw.githubusercontent.com/laurent22/rsync-time-backup/master/rsync_tmbackup.sh"
refreshPeriod = "168h"
