---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Information-Widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: custom
    url: https://search.home.lubui.com:8443/search?q=
    target: _blank
