numbered_command = true
xdg_open = false
xdg_open_fork = false
use_trash = true
watch_files = true

[display]
# default, hsplit
mode = "default"
automatically_count_files = false
collapse_preview = false
# ratios for parent view (optional), current view and preview
column_ratio = [1, 3, 4]
scroll_offset = 6
show_borders = false
show_hidden = false
show_icons = true
tilde_in_titlebar = true
# none, absolute, relative
line_number_style = "absolute"
# linemode = "size"

[display.sort]
# lexical, mtime, natural
method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 10000000000
preview_script = "~/.config/joshuto/preview_file.sh"

[search]
# insensitive, sensitive, smart
string_case_sensitivity = "insensitive"
# see above
glob_case_sensitivity = "sensitive"
# see above
regex_case_sensitivity = "sensitive"
# see above
fzf_case_sensitivity = "insensitive"

[tab]
# inherit, home, root
home_page = "home"
