[default_view]
keymap = [
  # 自定义配置
  { keys = [
    "h",
  ], commands = [
    "toggle_hidden",
  ] },
  { keys = [
    "m",
    "n",
    "q",
  ], commands = [
    "shell mount -t smbfs //urie@home.lubui.com/Public /Volumes/mnt/homeserver/",
    "cd /Volumes/mnt/homeserver/",
  ] },
  { keys = [
    "m",
    "u",
    "q",
  ], commands = [
    "shell diskutil umount /Volumes/mnt/homeserver/",
    "cd /Volumes/mnt/homeserver/",
  ] },
  { keys = [
    "m",
    "n",
    "w",
  ], commands = [
    "shell mount_webdav -s -i https://dav.home.lubui.com:8443/ /Volumes/mnt/homeserver/",
    "cd /Volumes/mnt/homeserver/",
  ] },
  { keys = [
    "b",
    "a",
  ], commands = [
    "add_bookmark",
  ] },
  { keys = [
    "g",
    "b",
  ], commands = [
    "cd_bookmark",
  ] },
  { keys = [
    "g",
    "z",
  ], commands = [
    "cd ~/.local/share/chezmoi",
  ] },
  { keys = [
    "z",
    " ",
  ], commands = [
    ":z ",
  ] },
  { keys = [
    "z",
    "i",
  ], commands = [
    ":zi ",
  ] },
  { keys = [
    "z",
    "t",
  ], commands = [
    "shell tar -czvf tmp.tar.gz %s",
  ] },
  { keys = [
    "escape",
  ], commands = [
    "select --all=true --deselect=true",
  ] },
  { keys = [
    "{",
  ], commands = [
    "cursor_move_up 5",
  ] },
  { keys = [
    "}",
  ], commands = [
    "cursor_move_down 5",
  ] },
  { keys = [
    "V",
  ], commands = [
    "toggle_visual",
  ] },
  { keys = [
    "v",
    "i",
  ], commands = [
    ":shell nvim ",
  ] },
  { keys = [
    "l",
    "g",
  ], commands = [
    "shell lazygit",
  ] },
  { keys = [
    "l",
    "z",
    "d",
  ], commands = [
    "shell lazydocker",
  ] },
  { keys = [
    "c",
    "o",
  ], commands = [
    ":shell code ",
  ] },
  { keys = [
    "c",
    "a",
  ], commands = [
    "shell chezmoi add %s",
  ] },
  { keys = [
    "c",
    "A",
  ], commands = [
    "shell chezmoi add --encrypt %s",
  ] },
  { keys = [
    "p",
    "s",
  ], commands = [
    "shell scp -r %s urie@home.lubui.com:~/temp",
  ] },
  { keys = [
    "p",
    "r",
  ], commands = [
    ":shell scp -r urie@home.lubui.com:~/",
  ] },
  { keys = [
    "Q",
  ], commands = [
    "close_tab",
  ] },
  { keys = [
    "q",
  ], commands = [
    "quit --output-current-directory",
  ] },
  { keys = [
    "1",
  ], commands = [
    "numbered_command 1",
  ] },
  { keys = [
    "2",
  ], commands = [
    "numbered_command 2",
  ] },
  { keys = [
    "3",
  ], commands = [
    "numbered_command 3",
  ] },
  { keys = [
    "4",
  ], commands = [
    "numbered_command 4",
  ] },
  { keys = [
    "5",
  ], commands = [
    "numbered_command 5",
  ] },
  { keys = [
    "6",
  ], commands = [
    "numbered_command 6",
  ] },
  { keys = [
    "7",
  ], commands = [
    "numbered_command 7",
  ] },
  { keys = [
    "8",
  ], commands = [
    "numbered_command 8",
  ] },
  { keys = [
    "9",
  ], commands = [
    "numbered_command 9",
  ] },
  { keys = [
    "0",
  ], commands = [
    "numbered_command 0",
  ] },
  # 默认配置
  { keys = [
    "T",
  ], commands = [
    "new_tab",
  ] },
  { keys = [
    "ctrl+t",
  ], commands = [
    "new_tab",
  ] },
  { keys = [
    "W",
  ], commands = [
    "close_tab",
  ] },
  { keys = [
    "ctrl+w",
  ], commands = [
    "close_tab",
  ] },
  { keys = [
    "R",
  ], commands = [
    "reload_dirlist",
  ] },
  # { keys = [ "z", "h" ],		commands = ["toggle_hidden"] },
  { keys = [
    "\t",
  ], commands = [
    "tab_switch 1",
  ] },
  { keys = [
    "backtab",
  ], commands = [
    "tab_switch -1",
  ] },
  { keys = [
    "alt+1",
  ], commands = [
    "tab_switch_index 1",
  ] },
  { keys = [
    "alt+2",
  ], commands = [
    "tab_switch_index 2",
  ] },
  { keys = [
    "alt+3",
  ], commands = [
    "tab_switch_index 3",
  ] },
  { keys = [
    "alt+4",
  ], commands = [
    "tab_switch_index 4",
  ] },
  { keys = [
    "alt+5",
  ], commands = [
    "tab_switch_index 5",
  ] },
  # arrow keys
  { keys = [
    "arrow_up",
  ], commands = [
    "cursor_move_up",
  ] },
  { keys = [
    "arrow_down",
  ], commands = [
    "cursor_move_down",
  ] },
  { keys = [
    "arrow_left",
  ], commands = [
    "cd ..",
  ] },
  { keys = [
    "arrow_right",
  ], commands = [
    "open",
  ] },
  { keys = [
    "\n",
  ], commands = [
    "open",
  ] },
  { keys = [
    "home",
  ], commands = [
    "cursor_move_home",
  ] },
  { keys = [
    "end",
  ], commands = [
    "cursor_move_end",
  ] },
  { keys = [
    "ctrl+u",
  ], commands = [
    "cursor_move_page_up 0.5",
  ] },
  { keys = [
    "ctrl+d",
  ], commands = [
    "cursor_move_page_down 0.5",
  ] },
  # vim-like keybindings
  { keys = [
    "j",
  ], commands = [
    "cursor_move_down",
  ] },
  { keys = [
    "k",
  ], commands = [
    "cursor_move_up",
  ] },
  # { keys = ["h"], commands = ["cd .."] },
  # { keys = [ "l" ],		commands = ["open"] },
  { keys = [
    "g",
    "g",
  ], commands = [
    "cursor_move_home",
  ] },
  { keys = [
    "G",
  ], commands = [
    "cursor_move_end",
  ] },
  # { keys = ["r"], commands = ["open_with"] },
  { keys = [
    "r",
  ], commands = [
    "shell open_file -s %s",
  ] },
  { keys = [
    "H",
  ], commands = [
    "cursor_move_page_home",
  ] },
  { keys = [
    "L",
  ], commands = [
    "cursor_move_page_middle",
  ] },
  { keys = [
    "M",
  ], commands = [
    "cursor_move_page_end",
  ] },
  { keys = [
    "page_up",
  ], commands = [
    "preview_cursor_move_up 10",
  ] },
  { keys = [
    "page_down",
  ], commands = [
    "preview_cursor_move_down 10",
  ] },
  { keys = [
    "c",
    "d",
  ], commands = [
    ":cd ",
  ] },
  { keys = [
    "d",
    "d",
  ], commands = [
    "cut_files",
  ] },
  { keys = [
    "y",
    "y",
  ], commands = [
    "copy_files",
  ] },
  { keys = [
    "p",
    "p",
  ], commands = [
    "paste_files",
  ] },
  { keys = [
    "p",
    "o",
  ], commands = [
    "paste_files --overwrite=true",
  ] },
  { keys = [
    "y",
    "n",
  ], commands = [
    "copy_filename",
  ] },
  { keys = [
    "y",
    ".",
  ], commands = [
    "copy_filename_without_extension",
  ] },
  { keys = [
    "y",
    "p",
  ], commands = [
    "copy_filepath",
  ] },
  { keys = [
    "y",
    "d",
  ], commands = [
    "copy_dirpath",
  ] },
  { keys = [
    "y",
    "l",
  ], commands = [
    "symlink_files --relative=true",
  ] },
  { keys = [
    "delete",
  ], commands = [
    "delete_files",
  ] },
  { keys = [
    "d",
    "D",
  ], commands = [
    "delete_files --noconfirm",
  ] },
  { keys = [
    "D",
    "D",
  ], commands = [
    "delete_files --permanently",
  ] },
  { keys = [
    "a",
  ], commands = [
    "rename_append",
  ] },
  { keys = [
    "A",
  ], commands = [
    "rename_prepend",
  ] },
  { keys = [
    "f",
    "t",
  ], commands = [
    ":touch ",
  ] },
  { keys = [
    " ",
  ], commands = [
    "select --toggle=true",
  ] },
  { keys = [
    "t",
  ], commands = [
    "select --all=true --toggle=true",
  ] },
  { keys = [
    "w",
  ], commands = [
    "show_tasks --exit-key=w",
  ] },
  { keys = [
    "b",
    "b",
  ], commands = [
    "bulk_rename",
  ] },
  { keys = [
    "=",
  ], commands = [
    "set_mode",
  ] },
  { keys = [
    ":",
  ], commands = [
    ":",
  ] },
  { keys = [
    ";",
  ], commands = [
    ":",
  ] },
  { keys = [
    "'",
  ], commands = [
    ":shell ",
  ] },
  { keys = [
    "m",
    "k",
  ], commands = [
    ":mkdir ",
  ] },
  { keys = [
    "c",
    "w",
  ], commands = [
    ":rename ",
  ] },
  { keys = [
    "/",
  ], commands = [
    ":search ",
  ] },
  { keys = [
    "|",
  ], commands = [
    ":search_inc ",
  ] },
  { keys = [
    "\\",
  ], commands = [
    ":search_glob ",
  ] },
  { keys = [
    "s",
  ], commands = [
    "search_fzf",
  ] },
  { keys = [
    "S",
  ], commands = [
    "subdir_fzf",
  ] },
  { keys = [
    "n",
  ], commands = [
    "search_next",
  ] },
  { keys = [
    "N",
  ], commands = [
    "search_prev",
  ] },
  { keys = [
    "o",
    "r",
  ], commands = [
    "sort reverse",
  ] },
  { keys = [
    "o",
    "l",
  ], commands = [
    "sort lexical",
  ] },
  { keys = [
    "o",
    "m",
  ], commands = [
    "sort mtime",
  ] },
  { keys = [
    "o",
    "n",
  ], commands = [
    "sort natural",
  ] },
  { keys = [
    "o",
    "s",
  ], commands = [
    "sort size",
  ] },
  { keys = [
    "o",
    "e",
  ], commands = [
    "sort ext",
  ] },
  { keys = [
    "g",
    "r",
  ], commands = [
    "cd /",
  ] },
  { keys = [
    "g",
    "c",
  ], commands = [
    "cd ~/.config",
  ] },
  { keys = [
    "g",
    "d",
  ], commands = [
    "cd ~/Downloads",
  ] },
  { keys = [
    "g",
    "e",
  ], commands = [
    "cd /etc",
  ] },
  { keys = [
    "g",
    "h",
  ], commands = [
    "cd ~/",
  ] },
  { keys = [
    "?",
  ], commands = [
    "help",
  ] },
]

[task_view]
keymap = [
  # arrow keys
  { keys = ["arrow_up"], commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["home"], commands = ["cursor_move_home"] },
  { keys = ["end"], commands = ["cursor_move_end"] },
  # vim-like keybindings
  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["k"], commands = ["cursor_move_up"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"], commands = ["cursor_move_end"] },
  { keys = ["w"], commands = ["show_tasks"] },
  { keys = ["escape"], commands = ["show_tasks"] },
]

[help_view]
keymap = [
  # arrow keys
  { keys = ["arrow_up"], commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["home"], commands = ["cursor_move_home"] },
  { keys = ["end"], commands = ["cursor_move_end"] },
  # vim-like keybindings
  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["k"], commands = ["cursor_move_up"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"], commands = ["cursor_move_end"] },
  { keys = ["w"], commands = ["show_tasks"] },
  { keys = ["escape"], commands = ["show_tasks"] },
]